import 'dart:math';
import 'package:prestpuesta/class/AceroAbilitado.dart';
import 'package:prestpuesta/class/Concreto.dart';
part "calculoZapata.dart";
part "calculoPiso.dart";
part "addMateri.dart";
part "calcMuro.dart";
part "calculoTrabe.dart";
part "categoria.dart";
